### ISSUE TITLE
Allow relativ keys for nested views

### ISSUE THREAD

**Issue by hqm42** [stefanoverna/vim-i18n#11]
I tried to add relative translations for my view in `app/views/admin/users/index.html.erb` but instead of `admin.users.index` i got `users.index` for a key.

**Comment by mauriciopasquier** [comment]
Yeah, I hit this issue too. It seems for a string `title` inside a file `index.html.erb` in this path `app/views/<ignored>/<last_dir>/index.html.erb` it generates:

```yml
en:
  last_dir:
    index:
      title: 'title'
```

but Rails (4.2.8 at least) would try to load:

```yml
en:
  ignored:
    last_dir:
      index:
        title: 'title'
```

PD: @stefanoverna: I'm so grateful for this plugin! You can't imagine how much time you saved me <3
